language_label: "عربی"
system_key: "arabic"

think_tanks:
  - name: "مركز روابط للبحوث والدراسات الاستراتيجية"
    url: "https://rawabetcenter.com"

  - name: "المعهد الأوراسي العربي للبحوث والدراسات"
    url: "https://eurasiaar.org"

  - name: "مركز بيان للدراسات والتخطيط"
    url: "https://bayancenter.org"

  - name: "مؤسسة آفاق للدراسات والنشر"
    url: "https://afaip.com"

  - name: "المركز المصري للفكر والدراسات الاستراتيجية"
    url: "https://ecss.com.eg"

  - name: "مركز الزيتونة للدراسات والاستشارات"
    url: "https://alzaytouna.net"

  - name: "مركز دراسات الوحدة العربية"
    url: "https://caus.org.lb"

  - name: "معهد دول الخليج العربي في واشنطن"
    url: "https://agsiw.org"

  - name: "مركز دراسات حقيقية"
    url: "https://truestudies.org"

  - name: "مركز تريندز للبحوث والاستشارات"
    url: "https://trendsgroup.org"

  - name: "المركز الأوروبي العربي للتدريب"
    url: "https://europarabct.com"

  - name: "رصانة - المعهد الدولي للدراسات الإيرانية"
    url: "https://rasanah-iiis.org"

  - name: "المركز الديمقراطي العربي"
    url: "https://democraticac.de"

  - name: "مركز الجزيرة للدراسات"
    url: "https://studies.aljazeera.net"

  - name: "مركز العروبة للدراسات والأبحاث"
    url: "https://orouba.ps"

  - name: "مركز حوار العراق"
    url: "https://hewariraq.com"

  - name: "مركز الأبعاد للدراسات والبحوث"
    url: "https://dimensionscenter.net"

  - name: "مركز الأهرام للدراسات السياسية والاستراتيجية"
    url: "https://acpss.ahram.org.eg"

  - name: "مركز المستقبل للأبحاث والدراسات المتقدمة"
    url: "https://futureuae.com"

  - name: "المركز العربي للأبحاث ودراسة السياسات"
    url: "https://www.dohainstitute.org"

  - name: "رصيف22"
    url: "https://raseef22.net"

  - name: "مركز الإمارات للسياسات"
    url: "https://epc.ae"

keywords:
  - "ايران"
  - "إيران"
  - "ايرانية"
  - "إيرانية"
  - "ايرانيون"
  - "إيرانيون"
  - "ايرانيين"
  - "إيرانيين"
  - "الايراني"
  - "الإيراني"
  - "الحرس الثوري"
  - "الجمهورية الاسلامية"
  - "الجمهورية الإسلامية"
  - "المرشد الاعلى"
  - "المرشد الأعلى"
  - "خامنئي"
  - "خامنائي"
  - "مضيق هرمز"
  - "هرمز"
  - "طهران"
  - "بزشكيان"
